CREATE TABLE WORDTABLE(
ID NUMBER PRIMARY KEY,
ENGLISHWORD VARCHAR(40),
MEANING VARCHAR(40)
);

CREATE TABLE MEMBER(
ID VARCHAR(40) PRIMARY KEY,
PASSWORD VARCHAR(40) );

SELECT * FROM MEMBER;

CREATE SEQUENCE ID_PK;

INSERT INTO WORDTABLE 
VALUES  ( ID_PK.nextval, 'absence','결석,부재,결근');
INSERT INTO WORDTABLE 
VALUES  ( ID_PK.nextval, 'absolute','완전한,확실한');
INSERT INTO WORDTABLE 
VALUES  ( ID_PK.nextval, 'confidence','신뢰,자신감');
INSERT INTO WORDTABLE 
VALUES  ( ID_PK.nextval, 'conference','회의,회견');

SELECT * FROM WORDTABLE ORDER BY ID;
SELECT * FROM WORDTABLE;